apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml
images:
- name: banana
  newName: registry.cn-hangzhou.aliyuncs.com/fruits/banana
  newTag: "20240815_2037"
patches:
- path: patch.yaml
