apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ./ingress.yaml

images:
- name: apple
  newName: registry.cn-hangzhou.aliyuncs.com/fruits/apple
  newTag: 0.0.2

patches:
- path: patch.yaml
