apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
spec:
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      imagePullSecrets:
        - name: youraccount
      containers:
      - name: apple
        image: apple:0.0.0
