apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana
spec:
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      labels:
        app: banana
    spec:
      imagePullSecrets:
        - name: youraccount
      containers:
      - name: banana
        image: banana:0.0.0
