apiVersion: v1
kind: Secret
metadata:
  name: animals
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://demo-gitlab.your.com/ops/animals.git
---
apiVersion: v1
kind: Secret
metadata:
  name: fruits
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://demo-gitlab.your.com/ops/fruits.git
---
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://demo-gitlab.your.com/ops
  username: root
  password: yourpass
